# Numpy

- Numpy is used for scientific computing in python.

In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 17.0 MB/s eta 0:00:0031m16.4 MB/s eta 0:00:01

[notice] A new release of pip is available: 25.0 -> 25.2
[notice] To update, run: pip install --upgrade pip


In [3]:
import numpy as np

print(np.__version__)

2.3.2


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5]) # 1D array
print(arr1)
print('shape', arr1.shape)

[1 2 3 4 5]
shape (5,)


In [ ]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # 2D array
print(arr2)
print('shape', arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape (2, 5)


In [10]:
np.ones((3, 4)) # 3 rows, 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange(1, 10, 2).reshape(5, 1) # 3 rows, 3 columns

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [13]:
np.eye(3) # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Vectorized operations
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([10, 20, 30, 40, 50])
print(arr3 + arr4)  # Element-wise addition

# Universal functions
print(np.sqrt(arr3))  # Square root of each element

[11 22 33 44 55]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [15]:
# Array slicing and indexing

arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr5[0, 1])  # Accessing element at row 0, column 1
print(arr5[:, 1])  # Accessing all rows, column 1
print(arr5[1, :])  # Accessing row 1, all columns
print(arr5[1:3, 0:2])  # Slicing rows 1 to 2, columns 0 to 1  

2
[2 5 8]
[4 5 6]
[[4 5]
 [7 8]]


In [ ]:
# some statistical concepts

# mean - 0 and std - 1 and calculate normalized array

arr6 = np.array([1, 2, 3, 4, 5])
print(np.mean(arr6))  # Mean
print(np.std(arr6))   # Standard deviation

normalized_arr = (arr6 - np.mean(arr6)) / np.std(arr6)
print(normalized_arr)  # Normalized array with mean 0 and std 1

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [19]:
# logical operations

arr7 = np.array([1, 2, 3, 4, 5])

print(arr7 > 3)  # Element-wise comparison
print(arr7[arr7 > 3])  # Filtering elements greater than 3
print(np.where(arr7 > 3, 'greater than 3', 'not greater than 3'))  # Conditional replacement


[False False False  True  True]
[4 5]
['not greater than 3' 'not greater than 3' 'not greater than 3'
 'greater than 3' 'greater than 3']
